# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import cv2
import qt_cv_camera
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_CamShow(object):
    def __init__(self):
        self.camera = qt_cv_camera.mycamera()

    def setupUi(self, CamShow):
        CamShow.setObjectName("CamShow")
        CamShow.resize(798, 593)
        self.centralwidget = QtWidgets.QWidget(CamShow)
        self.centralwidget.setObjectName("centralwidget")
        self.SettingFm = QtWidgets.QFrame(self.centralwidget)
        self.SettingFm.setGeometry(QtCore.QRect(20, 10, 331, 441))
        self.SettingFm.setFrameShape(QtWidgets.QFrame.Box)
        self.SettingFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SettingFm.setLineWidth(2)
        self.SettingFm.setObjectName("SettingFm")
        self.ColorFm = QtWidgets.QFrame(self.SettingFm)
        self.ColorFm.setGeometry(QtCore.QRect(30, 20, 271, 131))
        self.ColorFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColorFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorFm.setObjectName("ColorFm")
        self.checkBox = QtWidgets.QCheckBox(self.ColorFm)
        self.checkBox.setGeometry(QtCore.QRect(20, 10, 68, 16))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.ColorFm)
        self.label.setGeometry(QtCore.QRect(20, 40, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.ColorFm)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 21, 16))
        # 这里这个框和摄像头图像进行绑定
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.ColorFm)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 40, 160, 16))
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.ColorFm)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(50, 70, 160, 16))
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.ColorFm)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(50, 100, 160, 16))
        self.horizontalSlider_3.setMaximum(255)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")

        self.label_3 = QtWidgets.QLabel(self.ColorFm)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 16, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.ColorFm)
        self.spinBox.setGeometry(QtCore.QRect(220, 40, 42, 22))
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.ColorFm)
        self.spinBox_2.setGeometry(QtCore.QRect(220, 70, 42, 22))
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.ColorFm)
        self.spinBox_3.setGeometry(QtCore.QRect(220, 100, 42, 22))
        self.spinBox_3.setMaximum(255)
        self.spinBox_3.setObjectName("spinBox_3")
        self.MsgFm = QtWidgets.QFrame(self.centralwidget)
        self.MsgFm.setGeometry(QtCore.QRect(20, 470, 751, 71))
        self.MsgFm.setFrameShape(QtWidgets.QFrame.Box)
        self.MsgFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MsgFm.setLineWidth(2)
        self.MsgFm.setObjectName("MsgFm")
        self.opencm1 = QtWidgets.QPushButton(self.MsgFm)
        self.opencm1.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.opencm1.setObjectName("opencm1")
        self.opencm1.clicked.connect(self.opencm)

        self.opencm2 = QtWidgets.QPushButton(self.MsgFm)
        self.opencm2.setGeometry(QtCore.QRect(120, 10, 91, 31))
        self.opencm2.setObjectName("opencm2")
        self.opencm2.clicked.connect(self.closecm)

        self.DispFm = QtWidgets.QFrame(self.centralwidget)
        self.DispFm.setGeometry(QtCore.QRect(359, 9, 411, 441))
        self.DispFm.setFrameShape(QtWidgets.QFrame.Box)
        self.DispFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DispFm.setLineWidth(2)
        self.DispFm.setObjectName("DispFm")
        CamShow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CamShow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        CamShow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CamShow)
        self.statusbar.setObjectName("statusbar")
        CamShow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(CamShow)
        QtCore.QMetaObject.connectSlotsByName(CamShow)

    def retranslateUi(self, CamShow):
        _translate = QtCore.QCoreApplication.translate
        CamShow.setWindowTitle(_translate("CamShow", "MainWindow"))
        self.checkBox.setText(_translate("CamShow", "Gray"))
        self.label.setText(_translate("CamShow", "R"))
        self.label_2.setText(_translate("CamShow", "G"))
        self.label_3.setText(_translate("CamShow", "B"))
        self.opencm1.setText(_translate("CamShow", "开启摄像头"))
        self.opencm2.setText(_translate("CamShow", "关闭摄像头"))
        self.menu.setTitle(_translate("CamShow", "视频输入界面"))

    def opencm(self):
        # sender=self.sender()
        print("open", self.camera)
        self.camera.open()
        #flag,self.image=self.camera.cap.read()
        #show=cv2.resize(self.image)

    def closecm(self):
        self.camera.close()


if __name__ == '__main__':
    app = QApplication(sys.argv)  # 使用sys新建一个应用（Application）对象
    MainWindow = QMainWindow()  # 新建一个Qt中QMainWindow()类函数
    ui = Ui_CamShow()  # 定义ui，与我们设置窗体绑定
    ui.setupUi(MainWindow)  # 为MainWindow绑定窗体
    MainWindow.show()  # 将MainWindow窗体进行显示
    sys.exit(app.exec_())
